
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: asapp_db_admin
  password: asapp-db-pas
  host: localhost

development:
  <<: *default
  database: art_studio_app_development

test:
  <<: *default
  database: art_studio_app_test
